/**
 * Turn the built UI into a normal TypeScript module.
 *
 * The worker used to import `dist-mcp/index.html` as text, which worked only
 * because `wrangler.jsonc` declared a `Text` rule for that glob. That glob is
 * resolved relative to whichever repo is deploying — so an instance consuming
 * this library would have had to know about, and re-declare, the library's build
 * artefact. A generated `.ts` file is just an import: no rule, no ambient type,
 * nothing for the instance to know.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const root = join(import.meta.dir, "..");
const html = await Bun.file(join(root, "dist-mcp/index.html")).text();

if (!html.includes("<div id=")) {
  throw new Error("dist-mcp/index.html does not look like the built app");
}

await mkdir(join(root, "src/generated"), { recursive: true });
await writeFile(
  join(root, "src/generated/app-html.ts"),
  `// Generated by scripts/inline-app.ts from dist-mcp/index.html. Do not edit.\n` +
    `export const appBundleHtml = ${JSON.stringify(html)};\n`,
);

console.log(`inlined ${(html.length / 1024).toFixed(0)}KB into src/generated/app-html.ts`);
